"""Pure domain helpers (no Session, no FastAPI)."""
from app.domain.assignment import hours_exhausted, remaining_hours
from app.domain.classroom_rules import (
    ClassroomFact,
    PlacementContext,
    candidate_rooms_for,
    normalize_classroom_school_level,
    placement_cost,
    rank_candidate_rooms,
    room_allows,
    room_allows_level,
    room_allows_subject,
    room_allows_subgroup,
    room_denial_message,
    room_has_subject,
)
from app.domain.days import DAY_NAMES, SHORT_DAY_NAMES, fmt_time, time_range_label
from app.domain.names import normalize_person_name
from app.domain.pair_epochs import MAX_PAIR_LESSON, freeze_keys_for_good_doubles
from app.domain.schedule_facts import BusySlotFact, SlotFact, UnitFact
from app.domain.schedule_rules import (
    classroom_at_capacity,
    extra_singleton_days,
    groups_can_share_slot,
    leftover_singles_allowed,
    occupancy_blocks_unit,
    overlapping_classroom_busy,
    second_hour_is_split,
    slot_facts_conflict,
    slots_conflict,
    subject_day_limit_reached,
    teacher_busy_at_slot,
    teacher_class_day_limit_reached,
    time_intervals_overlap,
    units_cannot_share_class_slot,
)
from app.domain.school_class import (
    SPLIT_GRADE_BANDS,
    SPLIT_WHOLE_SHIFT,
    GradeBand,
    grade_bands_for_level,
    grade_from_name,
    level_from_grade,
    partition_classes_by_grade_bands,
)
from app.domain.shift_grid import (
    lesson_end_exclusive,
    lessons_count_on_day,
    weekly_slot_count,
)
from app.domain.school_level import level_label

__all__ = [
    "DAY_NAMES",
    "SHORT_DAY_NAMES",
    "fmt_time",
    "time_range_label",
    "grade_from_name",
    "level_from_grade",
    "GradeBand",
    "SPLIT_WHOLE_SHIFT",
    "SPLIT_GRADE_BANDS",
    "grade_bands_for_level",
    "partition_classes_by_grade_bands",
    "level_label",
    "lessons_count_on_day",
    "lesson_end_exclusive",
    "weekly_slot_count",
    "normalize_person_name",
    "remaining_hours",
    "hours_exhausted",
    "slots_conflict",
    "slot_facts_conflict",
    "time_intervals_overlap",
    "leftover_singles_allowed",
    "extra_singleton_days",
    "second_hour_is_split",
    "subject_day_limit_reached",
    "teacher_class_day_limit_reached",
    "groups_can_share_slot",
    "units_cannot_share_class_slot",
    "occupancy_blocks_unit",
    "teacher_busy_at_slot",
    "overlapping_classroom_busy",
    "classroom_at_capacity",
    "UnitFact",
    "SlotFact",
    "BusySlotFact",
    "ClassroomFact",
    "PlacementContext",
    "normalize_classroom_school_level",
    "room_allows",
    "room_allows_level",
    "room_allows_subject",
    "room_allows_subgroup",
    "room_denial_message",
    "room_has_subject",
    "placement_cost",
    "rank_candidate_rooms",
    "candidate_rooms_for",
    "freeze_keys_for_good_doubles",
    "MAX_PAIR_LESSON",
]
